In [5]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
print(tf.__version__)

2.2.0


In [0]:
Sentences = [
             "I love my dog",
             "I love my cat",
             "I hate your dog!!",
             "Do you think my dog is amazing"
]

In [10]:
tokenizer = Tokenizer(num_words=100, oov_token="OOV")
tokenizer.fit_on_texts(Sentences)
word_index = tokenizer.word_index

sequences = tokenizer.texts_to_sequences(Sentences)
padded = pad_sequences(sequences)

print(word_index)
print(sequences)
print(padded)

{'OOV': 1, 'i': 2, 'my': 3, 'dog': 4, 'love': 5, 'cat': 6, 'hate': 7, 'your': 8, 'do': 9, 'you': 10, 'think': 11, 'is': 12, 'amazing': 13}
[[2, 5, 3, 4], [2, 5, 3, 6], [2, 7, 8, 4], [9, 10, 11, 3, 4, 12, 13]]
[[ 0  0  0  2  5  3  4]
 [ 0  0  0  2  5  3  6]
 [ 0  0  0  2  7  8  4]
 [ 9 10 11  3  4 12 13]]


## **Covert the sentences to same length in a matrix**

In [12]:
padded = pad_sequences(sequences, padding='post')
print(padded)

[[ 2  5  3  4  0  0  0]
 [ 2  5  3  6  0  0  0]
 [ 2  7  8  4  0  0  0]
 [ 9 10 11  3  4 12 13]]


In [13]:
padded = pad_sequences(sequences, padding='post', truncating='post', maxlen=5)
print(padded)

[[ 2  5  3  4  0]
 [ 2  5  3  6  0]
 [ 2  7  8  4  0]
 [ 9 10 11  3  4]]


# **Max length of string can be selected using maxlen. Truncating default is pre. We can switch it to post.**